name: Publish to Sonatype
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven Central
    uses: entur/gha-maven-central/.github/workflows/gradle-publish.yml@brand-new
    secrets: inherit